services:
  app-csv:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
# services:
#   web-server:
#     build:
#       context: .
#       dockerfile: Dockerfile
#     volumes:
#       - .:/app
#     ports:
#      - '80:80'